### PR TITLE
add: hex and bin

### PR DESCRIPTION
**Pull request by ronanlv**
Greetings,

This is my first time that I 'pull request'.
I've added, binary and hexadecimal number support 
(starting with '0b' and '0x' respectively)

Regards
Ronan

### CODE REVIEW

**Comment by cgjosephlee** [comment]
Hi Ronan,

Thank you for your efforts! Would you kindly update the examples in readme as well?

Best,
Joseph

**Comment by ronanlv** [comment]
Hi

I have edited the readme file!

Greetings
Ronan

**Comment by cgjosephlee** [comment]
Hi,

I would like to keep main page and code style tidy so I made some revisions.
I think it's ready to merge, looking forward to your review.

Best,
Joseph

**Comment by cgjosephlee** [comment]
I'm merging it to `master`, thank you for your efforts.

**Comment by ronanlv** [comment]
Hi,

Sorry didn't saw your last email.
Thanks!

Ronan

Op do 30 mei 2019 om 03:53 schreef Joseph Lee <notifications@github.com>:

**Pull request merged**
